# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://localhost:5000/rpc?XDEBUG_SESSION_START=15193
Authorization: Bearer Debug-User-Id:2
Content-Type: application/json

{
  "method": "loginByWechat",
  "params": {
    "app_name": "auth",
    "code": "abcd"
  }
}

###

POST http://localhost:5000/rpc?XDEBUG_SESSION_START=17185
Authorization: Bearer Debug-User-Id:2
Content-Type: application/json

{
  "method": "register",
  "params": {
    "app_name": "auth",
    "username": "subarashii",
    "password": "123456"
  }
}

###

POST http://localhost:5000/rpc?XDEBUG_SESSION_START=17185
Authorization: Bearer Debug-User-Id:2
Content-Type: application/json

{
  "method": "loginByPassword",
  "params": {
    "app_name": "auth",
    "username": "good to go",
    "password": "123456"
  }
}

###

POST http://localhost:5000/rpc?XDEBUG_SESSION_START=17185
Authorization: Bearer Debug-User-Id:2
Content-Type: application/json

{
  "method": "loginByToken",
  "params": {
    "app_name": "auth",
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNiwiYXBwIjoiYXV0aCIsImV4cCI6MTU3MjMxOTgwMn0._6qmLcf8mO2YICK7Ol8513zV-7uo8s7xZPZRl3qoUII"
  }
}

###

POST http://localhost:5000/rpc?XDEBUG_SESSION_START=17185
Content-Type: application/json

{
  "method": "loginAsGuest",
  "params": {
    "app_name": "auth",
    "userId": 14
  }
}

###

POST http://localhost:5000/rpc?XDEBUG_SESSION_START=17185
Content-Type: application/json

{
  "method": "bindWechat",
  "params": {
    "id": 3,
    "app_name": "auth",
    "code": "123456"
  }
}

###

POST http://localhost:5000/rpc?XDEBUG_SESSION_START=17185
Content-Type: application/json

{
  "method": "bindPassword",
  "params": {
    "id": 1,
    "app_name": "auth",
    "username": "big bang",
    "password": "45678"
  }
}

###

POST http://localhost:5000/rpc?XDEBUG_SESSION_START=19763
Content-Type: application/json

{
  "method": "getOpenid",
  "params": {
    "id": 2,
    "app_name": "sea"
  }
}

###
